### ISSUE TITLE
Hi Guys, I'd like to know if you would release the english version

### ISSUE THREAD

**Issue by alvarolordelo** [swoole-foundation/yii2-swoole-extension#1]
Thanks for the great job done here, is it possible to you make it on english language, since woole team has good professionals, thanks in advance.

**Comment by xialeistudio** [comment]
Thanks for your suggestion!
I will finish the job as soon as possible
 
---Original---

**Comment by alvarolordelo** [comment]
> Thanks for your suggestion! I will finish the job as soon as possible
> […](#)
> ---Original--- From: "Álvaro Lordêlo"<notifications@github.com&gt; Date: Thu, Sep 5, 2019 09:57 AM To: "swoole-foundation/yii2-swoole-extension"<yii2-swoole-extension@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [swoole-foundation/yii2-swoole-extension] Hi Guys, I'd like to know if you would release the english version (#1) Thanks for the great job done here, is it possible to you make it on english language, since woole team has good professionals, thanks in advance. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Do you have Wechat(weixin) or skype?

**Comment by xialeistudio** [comment]
I released a english version.

My wechat is `xialei-vip`.
